### ISSUE TITLE
Dedicated server steam authentication failed

### ISSUE THREAD

**Issue by CelestialCosmic** [Regalis11/Barotrauma#13210]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- My issue happened while using mods.

### What happened?

port forwarded using frp,but only host can join the server,guest will fail with error message "steam authentication failed"

### Reproduction steps

using windows11 and dedicated server in game directory
server is an ubuntu bought from www.huaweicloud.com

using mods(provided by my friend)
![photo_2023-12-21_19-34-04](https://github.com/Regalis11/Barotrauma/assets/89504915/770b3e74-69fe-4e4b-a163-47521d204d3b)
these are submarines form workshop

part of frpc.toml
```toml
serverAddr = "example"
serverPort = 19000

[[proxies]]
name = "remote"
type = "udp"
localIP = "127.0.0.1"
localPort = 27015
remotePort = 27015

[[proxies]]
name = "remote2"
type = "udp"
localIP = "127.0.0.1"
localPort = 27016
remotePort = 27016
```

frp_debug.bat
```bat
".\frpc.exe" -c ".\frpc.toml"
pause
```

part of serversettings.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<serversettings
  name="example"
  port="27015"
  queryport="27016"
  password="114514"
  enableupnp="true"
  autorestart="true"
  LevelDifficulty="0"
  ServerMessage=""
  HiddenSubs=""
```

steps I ask them to start the dedicated server
host:
1. start DedicatedServer.exe
2. start frp_debug.bat
3. start game from steam

after server started
host can join server using both 127.0.0.1 and remote ip
guest connect remote ip will get error message as follows:
![2023-12-21_19-43](https://github.com/Regalis11/Barotrauma/assets/89504915/590e4ff2-c39d-41c0-93ca-c548d5c0a523)

no matter what I try,every tries fail.

Note:steam p2p is working normally,with acceptable lags(mostly less than 200ms)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows
